modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"
#issueTrackerURL="https://github.com/Example/Example/issues" #optional
[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://github.com/Example/Example" #optional
logoFile="icon.png" #optional
credits="MehVahdJukaar for Amendments, iron431 for Iron's Spells 'n Spellbooks" #optional
authors="${mod_authors}"
#displayTest="MATCH_VERSION" #optional
description='''${mod_description}'''
[[dependencies.${mod_id}]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${forge_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="irons_spellbooks"
    mandatory=true
    versionRange="${iss_version_range}"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="amendments"
    mandatory=true
    versionRange="${amendments_version_range}"
    ordering="AFTER"
    side="BOTH"